name: Release

on:
  release:
    types: [published, edited] # This captures both new releases and updates to existing ones
  workflow_dispatch: # Keeps your ability to run it manually

jobs:
  release:
    runs-on: windows-latest

    permissions:
      contents: write 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        dotnet-quality: 'preview'

    - name: Publish PKHeX
      run: dotnet publish PKHeX.WinForms/PKHeX.WinForms.csproj --configuration Release --output publish_output

    - name: Create Zip Archive
      run: Compress-Archive -Path publish_output\* -DestinationPath PKHeX-EmeraldLegacy.zip

    - name: Create or Update GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: PKHeX-EmeraldLegacy.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
